### ISSUE TITLE
infinte redirects

### ISSUE THREAD

**Issue by j2l** [brettt89/silverstripe-web#54]
Hello,
I'm discovering silverstripe and already know docker and I start and manage containers using portainer.
I did `composer create-project silverstripe/installer sstest` locally.
Added _ss_environment.php (not sure it's needed anymore): 
```
 <?php
/* Change this from 'dev' to 'live' for a production environment. */
define('SS_ENVIRONMENT_TYPE', 'dev');

/* This defines a default database user */
define('SS_DATABASE_SERVER', 'database');
define('SS_DATABASE_NAME', 'SS_mysite');
define('SS_DATABASE_USERNAME', 'root');
define('SS_DATABASE_PASSWORD', '');

/* Configure a default username and password to access the CMS on all sites in this environment. */
define('SS_DEFAULT_ADMIN_USERNAME', 'admin');
define('SS_DEFAULT_ADMIN_PASSWORD', 'password');

// This is used by sake to know which directory points to which URL
global $_FILE_TO_URL_MAPPING;
$_FILE_TO_URL_MAPPING['/var/www/html'] = 'http://localhost';
```
BTW, without it, it throws the same error at the end.
My "docker.compose" (as a portainer stack):
```
version: "3.8"
services:
  silverstripe:
    image: brettt89/silverstripe-web:7.4-apache
    volumes:
       - /media/pm/Data/Documents/docker/sstest:/var/www/html
    ports:
       - 8080:80
    depends_on:
       - database
    environment:
       - DOCUMENT_ROOT=/var/www/html/public
       - SS_TRUSTED_PROXY_IPS=*
       - SS_ENVIRONMENT_TYPE=dev
       - SS_DATABASE_SERVER=database
       - SS_DATABASE_NAME=SS_mysite
       - SS_DATABASE_USERNAME=root
       - SS_DATABASE_PASSWORD=
       - SS_DEFAULT_ADMIN_USERNAME=admin
       - SS_DEFAULT_ADMIN_PASSWORD=password

  database:
    image: mysql:5.7
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
       - db-data:/var/lib/mysql
volumes:
     db-data:
```
At http://localhost:8080 I get
`Internal Server Error`
In container logs I get:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.11.3. Set the 'ServerName' directive globally to suppress this message
[Fri Apr 23 16:30:04.411013 2021] [core:error] [pid 18] [client 10.0.0.2:44344] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
```
Note that in the container /etc/apache2/avail... has ServerName = localhost by default.

Ubuntu 20.04
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
PHP is 7.4.3
Composer 1.10.1 2020-03-13 20:34:27

Any idea?
Thanks!
