### ISSUE TITLE
Support for arm64 

### ISSUE THREAD

**Issue by bummzack** [brettt89/silverstripe-web#58]
It would be really nice if these images were also available for `arm64`, eg. Apple Silicon.

**Comment by davejtoews** [comment]
Not clear to me what it would take to modify this repository to make it possible, but it does appear that the images this is built on may be available in arm64 versions: https://hub.docker.com/layers/php/library/php/7.4-apache-buster/images/sha256-82e3b6da5a55ad97e4ca149332d7f275c57171a67f4748864ddd59b57910cfaf?context=explore

**Comment by davejtoews** [comment]
Figured out a temporary workaround.

Might be off base here but it seems to me the issue is that including the below delivers a _built_ docker image to your machine.

```
services:
  web:
    image: brettt89/silverstripe-web:7.4-apache
```

With no arm64 version available, docker pulls in the amd64 version.

But, since docker can build images locally, on an M1 machine you can replace the above code with the following.

```
services:
  web:
    build:
      context: https://raw.githubusercontent.com/brettt89/silverstripe-docker/master/src/7.4/apache/buster/Dockerfile
    platform: linux/arm64/v8
```

The platform line may be redundant. I've got this running now on local without the `amd64` flag on the container indicating that it's running through the rosetta emulation layer.
